<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Cronus.Server.Host</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cronus.Common\Cronus.Common.csproj" />
    <ProjectReference Include="..\Cronus.Data\Cronus.Data.csproj" />
    <ProjectReference Include="..\Cronus.Domain\Cronus.Domain.csproj" />
    <ProjectReference Include="..\Cronus.Database\Cronus.Database.csproj" />
    <ProjectReference Include="..\Cronus.Network\Cronus.Network.csproj" />
    <ProjectReference Include="..\Cronus.Scripting\Cronus.Scripting.csproj" />
    <ProjectReference Include="..\Cronus.Server.Login\Cronus.Server.Login.csproj" />
    <ProjectReference Include="..\Cronus.Server.Game\Cronus.Server.Game.csproj" />
    <ProjectReference Include="..\Cronus.Server.Channel\Cronus.Server.Channel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Cronus.Server.Game" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\data\opcodes\*.properties" Link="opcodes\%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
