<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cronus.Common\Cronus.Common.csproj" />
    <ProjectReference Include="..\Cronus.Domain\Cronus.Domain.csproj" />
    <ProjectReference Include="..\Cronus.Network\Cronus.Network.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
  </ItemGroup>

</Project>
