<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cronus.Common\Cronus.Common.csproj" />
    <ProjectReference Include="..\Cronus.Network\Cronus.Network.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\data\opcodes\*.properties" Link="opcodes\%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
