<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cronus.Common\Cronus.Common.csproj" />
    <ProjectReference Include="..\Cronus.Data\Cronus.Data.csproj" />
    <ProjectReference Include="..\Cronus.Domain\Cronus.Domain.csproj" />
    <ProjectReference Include="..\Cronus.Network\Cronus.Network.csproj" />
    <ProjectReference Include="..\Cronus.Server.Login\Cronus.Server.Login.csproj" />
  </ItemGroup>

</Project>
